# Generated by Django 4.0 on 2021-12-12 17:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
            options={
                'ordering': ('-name',),
            },
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('suggested', 'SUGGESTED'), ('implemented', 'IMPLEMENTED'), ('rejected', 'REJECTED')], default='suggested', max_length=20)),
                ('body', models.TextField()),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='recommend.metric')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='recommend.team')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
