# Generated by Django 4.0 on 2021-12-12 17:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recommendation',
            options={},
        ),
        migrations.RemoveField(
            model_name='recommendation',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='recommendation',
            name='status',
        ),
        migrations.RemoveField(
            model_name='recommendation',
            name='team',
        ),
        migrations.CreateModel(
            name='SuggestedRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('suggested', 'SUGGESTED'), ('implemented', 'IMPLEMENTED'), ('rejected', 'REJECTED')], default='suggested', max_length=20)),
                ('recommendation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='recommend.recommendation')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='recommend.team')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
